using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartSports.Api.Migrations
{
    public partial class UpdatePersistentAiChatSnapshot : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AiChatConversations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ConversationId" text NOT NULL,
                    "UserId" integer NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_AiChatConversations_ConversationId"
                    ON "AiChatConversations" ("ConversationId");
                CREATE TABLE IF NOT EXISTS "AiChatConversationMessages" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "AiChatConversationId" integer NOT NULL,
                    "MessageId" text NOT NULL,
                    "Role" text NOT NULL,
                    "Content" text NOT NULL,
                    "SourcesJson" text NOT NULL,
                    "TimestampUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_AiChatConversationMessages_AiChatConversations_AiChatConversationId"
                        FOREIGN KEY ("AiChatConversationId")
                        REFERENCES "AiChatConversations" ("Id")
                        ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS "IX_AiChatConversationMessages_AiChatConversationId"
                    ON "AiChatConversationMessages" ("AiChatConversationId");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "AiChatConversationMessages";
                DROP TABLE IF EXISTS "AiChatConversations";
                """);
        }
    }
}
