import BookingList from '../components/BookingList'
import SchedulePanel from '../components/SchedulePanel'

export default function OverviewPage({ heroMessage, stats, facilities, bookings, support, schedule, onBooking, onAIRequest, onTicket, onFacilities, onSchedule, onBookings, onDetails, onTeam, onNotice }) {
  return (
    <>
      <section className="hero-panel"><div className="hero-copy"><span className="chip">Open all week</span><h2>{heroMessage}</h2><p>Reserve premium courts, track training time, and manage your active schedule in one place.</p><div className="hero-actions"><button className="primary-btn" onClick={onBooking}>Book a facility</button><button className="secondary-btn light" onClick={onBookings}>View calendar</button></div></div><div className="hero-summary"><div className="summary-card"><p>Next session</p><strong>Badminton Doubles</strong><span>Today • 6:30 PM</span></div><div className="mini-metrics"><div><strong>12</strong><span>Open courts</span></div><div><strong>4.9</strong><span>Rating</span></div></div></div></section>
      <section className="stats-grid">{stats.map((stat) => <article key={stat.label} className={`stat-card ${stat.tone}`}><span>{stat.label}</span><strong>{stat.value}</strong></article>)}</section>
      <section className="content-grid"><div className="panel"><div className="panel-header"><h3>Popular facilities</h3><button className="text-action" type="button" onClick={onFacilities}>See all</button></div><div className="facility-list">{facilities.map((facility) => <div key={facility.name} className={`facility-card ${facility.accent}`}><div className="facility-icon">{facility.icon}</div><div className="facility-body"><div className="facility-topline"><h4>{facility.name}</h4><span>{facility.type}</span></div><div className="facility-meta"><strong>{facility.price}</strong><small>{facility.status}</small></div></div></div>)}</div></div><aside className="panel side-panel"><div className="panel-header"><h3>Quick actions</h3></div><div className="action-list"><button type="button" className="action-chip" onClick={onBooking}>Book court</button><button type="button" className="action-chip" onClick={onAIRequest}>Ask AI to find a facility</button><button type="button" className="action-chip" onClick={onSchedule}>View schedule</button><button type="button" className="action-chip" onClick={onTeam}>Manage team</button><button type="button" className="action-chip" onClick={() => onNotice('Rewards are available after your first completed booking.')}>Rewards</button></div><div className="reward-card"><p>Member reward</p><strong>12 points</strong><span>Earned this week</span></div></aside></section>
      <section className="lower-grid"><div className="panel"><div className="panel-header"><h3>Upcoming bookings</h3><button className="text-action" type="button" onClick={onBookings}>All bookings</button></div><BookingList bookings={bookings} /></div><div className="panel"><div className="panel-header"><h3>Support requests</h3><button className="text-action" type="button" onClick={onTicket}>New request</button></div><div className="support-list">{support.map((item) => <div key={item.title} className="support-item"><div><strong>{item.title}</strong><p>{item.detail}</p></div><span className="priority-tag">{item.priority}</span></div>)}</div></div></section>
      <SchedulePanel schedule={schedule} onDetails={onDetails} onOpenCalendar={onBookings} />
    </>
  )
}
